# Generated by Django 4.1.3 on 2023-02-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.TextField(null=True),
        ),
    ]
