# Generated by Django 4.1.3 on 2023-02-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
    ]
